# Generated by Django 4.2.20 on 2025-09-03 20:50

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='default/avatar/default_avatar.jpg', upload_to=gallery.models.persons_photos_path, verbose_name='Фото'),
        ),
    ]
