# Generated by Django 4.2.20 on 2025-09-04 10:16

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='backdrop',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.films_photos_path, verbose_name='Обои'),
        ),
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.films_photos_path, verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.films_photos_path, verbose_name='Постер'),
        ),
    ]
