# Generated by Django 4.2.20 on 2026-03-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_film_backdrop_alter_film_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='series_length',
        ),
        migrations.RemoveField(
            model_name='film',
            name='total_series_length',
        ),
        migrations.AlterField(
            model_name='film',
            name='rating_mpaa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Рейтиг MPAA: pg-13, R и тд.'),
        ),
    ]
