# Generated by Django 4.2.20 on 2026-03-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_film_series_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='is_series',
        ),
    ]
