# Generated by Django 4.2.20 on 2026-04-06 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_film_is_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['year', 'id'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDb'),
        ),
        migrations.AddField(
            model_name='film',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг Кинопоиска'),
        ),
    ]
