# Generated by Django 4.2.20 on 2026-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_film_options_film_imdb_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmnetwork',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmnetwork',
            name='network',
        ),
        migrations.RemoveField(
            model_name='film',
            name='backdrop',
        ),
        migrations.RemoveField(
            model_name='film',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='film',
            name='networks',
        ),
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
        migrations.AddField(
            model_name='film',
            name='backdrop_preview_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на маленькие Обои'),
        ),
        migrations.AddField(
            model_name='film',
            name='backdrop_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Обои'),
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_votes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество оценок на imdb'),
        ),
        migrations.AddField(
            model_name='film',
            name='kinopoisk_votes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество оценок на кинопоиске'),
        ),
        migrations.AddField(
            model_name='film',
            name='logo_preview_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на маленькое Лого'),
        ),
        migrations.AddField(
            model_name='film',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Лого'),
        ),
        migrations.AddField(
            model_name='film',
            name='poster_preview_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на маленький постер'),
        ),
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на постер'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='place',
            field=models.CharField(max_length=50, verbose_name='Место сборов (США, Мир, Россия)'),
        ),
        migrations.DeleteModel(
            name='AgregatorInfo',
        ),
        migrations.DeleteModel(
            name='FilmNetwork',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
