# Generated by Django 4.2.20 on 2026-04-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_filmnetwork_film_remove_filmnetwork_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Например: kinopoisk_movies', max_length=100, unique=True, verbose_name='Источник')),
                ('next_cursor', models.TextField(blank=True, null=True, verbose_name='Курсор следующей страницы')),
                ('last_successful_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный запуск')),
                ('last_completed_sync_at', models.DateTimeField(blank=True, help_text='Заполняется, когда дошли до конца выборки', null=True, verbose_name='Когда полностью закончили проход')),
                ('pages_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано страниц')),
                ('movies_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано фильмов')),
                ('movies_saved', models.PositiveIntegerField(default=0, verbose_name='Сохранено/обновлено фильмов')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Последняя ошибка')),
                ('is_running', models.BooleanField(default=False, verbose_name='Импорт сейчас выполняется')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние импорта',
                'verbose_name_plural': 'Состояния импорта',
                'ordering': ['source'],
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, default='default/avatar/default_avatar.jpg', max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AddConstraint(
            model_name='filmcountry',
            constraint=models.UniqueConstraint(fields=('film', 'country'), name='unique_film_country'),
        ),
        migrations.AddConstraint(
            model_name='filmgenre',
            constraint=models.UniqueConstraint(fields=('film', 'genre'), name='unique_film_genre'),
        ),
        migrations.AddConstraint(
            model_name='filmpersonprofession',
            constraint=models.UniqueConstraint(fields=('film_person', 'profession'), name='uniq_film_person_profession'),
        ),
        migrations.AddConstraint(
            model_name='sequelsandprequels',
            constraint=models.UniqueConstraint(fields=('film', 'related_film'), name='uniq_sequel_prequel'),
        ),
        migrations.AddConstraint(
            model_name='similarfilms',
            constraint=models.UniqueConstraint(fields=('film', 'similar_film'), name='uniq_similar_film'),
        ),
    ]
