# Generated by Django 4.2.20 on 2026-04-25 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0008_importstate_remove_person_photo_person_photo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_top_entries', to='gallery.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_films', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='usertopfilm',
            constraint=models.UniqueConstraint(fields=('user', 'position'), name='unique_user_top_position'),
        ),
        migrations.AddConstraint(
            model_name='usertopfilm',
            constraint=models.UniqueConstraint(fields=('user', 'film'), name='unique_user_top_film'),
        ),
        migrations.AddConstraint(
            model_name='usertopfilm',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 10)), name='user_top_film_position_1_10'),
        ),
    ]
