# Generated by Django 4.2.20 on 2025-10-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilmactivitie',
            old_name='is_wathed',
            new_name='is_watched',
        ),
    ]
