# Generated by Django 4.2.20 on 2026-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_is_wathed_userfilmactivitie_is_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilmactivitie',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный'),
        ),
    ]
