# Generated by Django 4.2.20 on 2026-02-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_userfilmactivitie_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionfilms',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionfilms',
            name='film',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionFilms',
        ),
    ]
