# Generated by Django 4.2.20 on 2026-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_collectionfilms_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilmactivitie',
            name='is_public',
        ),
        migrations.AddField(
            model_name='userfilmactivitie',
            name='is_public_for_planned',
            field=models.BooleanField(default=True, verbose_name='Публичный для планируемого'),
        ),
        migrations.AddField(
            model_name='userfilmactivitie',
            name='is_public_for_watched',
            field=models.BooleanField(default=True, verbose_name='Публичный для просмотренного'),
        ),
    ]
