# Generated by Django 4.2.20 on 2026-03-09 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0005_remove_film_is_series'),
        ('activities', '0005_remove_userfilmactivitie_is_public_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFilmActivitie',
            new_name='UserFilmActivity',
        ),
    ]
