# Generated by Django 4.2.20 on 2026-04-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_film_options_film_imdb_rating_and_more'),
        ('activities', '0006_rename_userfilmactivitie_userfilmactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilmactivity',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_activities', to='gallery.film', verbose_name='Фильм'),
        ),
    ]
