# Generated by Django 4.2.20 on 2026-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_userfilmactivity_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilmactivity',
            name='watched_at',
            field=models.DateTimeField(blank=True, help_text='Когда фильм был отмечен как просмотренный', null=True, verbose_name='Дата просмотра'),
        ),
    ]
