# Generated by Django 4.2.20 on 2026-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_userfilmactivity_watched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilmactivity',
            name='planned_at',
            field=models.DateTimeField(blank=True, help_text='Когда фильм был отмечен как планируемый', null=True, verbose_name='Дата добавления в планируемые'),
        ),
    ]
