# Generated by Django 4.2.20 on 2026-04-26 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0009_usertopfilm_usertopfilm_unique_user_top_position_and_more'),
        ('activities', '0009_userfilmactivity_planned_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreview',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий к рецензии', 'verbose_name_plural': 'Комментарии к рецензиям'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
        migrations.AddField(
            model_name='commentreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='Есть спойлеры'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('positive', 'Положительная'), ('neutral', 'Нейтральная'), ('negative', 'Отрицательная')], db_index=True, default='neutral', max_length=16, verbose_name='Тип рецензии'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок рецензии'),
        ),
        migrations.AlterField(
            model_name='commentreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='commentreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.review', verbose_name='Рецензия'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gallery.film', verbose_name='Фильм'),
        ),
        migrations.AddIndex(
            model_name='commentreview',
            index=models.Index(fields=['review', 'created_at'], name='activities__review__9d9a39_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['film', '-created_at'], name='activities__film_id_3c9532_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['film', 'review_type'], name='activities__film_id_926652_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'film'), name='unique_author_film_review'),
        ),
    ]
