# Максимальные значения длины для полей
NAME_MAX_LENGTH = 50
PERSON_NAME_MAX_LENGTH = 100
FILM_TITLE_MAX_LENGTH = 255
SHORT_DESC_MAX_LENGTH = 500
SLOGAN_MAX_LENGTH = 255
RATING_MPAA_MAX_LENGTH = 10
BUDGET_CURRENCY_MAX_LENGTH = 10
MOVIE_CHARACTER_MAX_LENGTH = 255
URL_MAX_LENGTH = 255
VIDEO_TITLE_MAX_LENGTH = 255
PROFESSION_MAX_LENGTH = 30

# Ограничения по длине в строковых методах
CUT_FACT_TEXT = 30
CUT_FILM_NAME = 30
CUT_PERSON_NAME = 20
CUT_VIDEO_NAME = 20

# Ограничения в валидаторах
FIRST_FILM_YEAR = 1888
MAX_MOVIE_LENGTH = 1000
MIN_MOVIE_LENGTH = 1

# Другое
MAX_FUTURE_PERIOD_RELEASE = 100
