# Generated by Django 4.2.20 on 2025-06-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photopost_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='uploaded_at',
        ),
    ]
