# Generated by Django 4.2.20 on 2026-03-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MODERATOR', 'Модератор'), ('USER', 'Пользователь')], default='USER', max_length=20, verbose_name='Роль'),
        ),
    ]
