# Generated by Django 4.2.20 on 2026-02-23 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_alter_film_backdrop_alter_film_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подборки')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание подборки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompilationsFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compilations.compilation', verbose_name='Подборка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.film', verbose_name='Фильм')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='compilation',
            name='films',
            field=models.ManyToManyField(through='compilations.CompilationsFilms', to='gallery.film', verbose_name='Фильмы'),
        ),
        migrations.AddField(
            model_name='compilation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
